# Tweak this parameter according to your platform
# You can alternative have predefined values depending on the platform (See libsgxstep/config.h)
# Too high values will skip instructions
# Too small values will be stuck zero stepping or might produce errors
SGX_STEP_TIMER_INTERVAL = 41

# Number of times the loop should be run
NUM = 10000

## Choose between MICROBENCH or IPP_LIB here
ATTACK_SCENARIO = MICROBENCH

# ---- Parameters for the IPP_LIB ATTACK_SCENARIO
# Set ATTACKER_SYNC to 0 to simulate the original IPP library
# without an attacker synchronizing instructions in the same core
# This parameter is only used if ATTACK_SCENARIO is set to IPP_LIB
ATTACKER_SYNC = 1

# ---- Parameters for the MICROBENCH ATTACK_SCENARIO
# The following parameters are only relevant when
# the ATTACK_SCENARIO is set to MICROBENCH
# and are ignored if ATTACK_SCENARIO == IPP_LIB

# Alignment of the if branch. Should be a value between 0-15
# Important: This variable must be set!
ALIGN1=6

# Alignment of the else branch. Should be a value between 0-15
# Important: This variable must be set!
ALIGN2=3

# Number of pairs of (test-mov) per branch
NUM_INSTR = 25


# ---- PCM Variables
PCM_ENABLED = 0
# Add events here.
# Max four events at the same time can be recorded.
# See the skylake_events file for a list of supported performance counters
EVENTS += "UOPS_ISSUED.ANY-event=0xe,umask=0x1"

